import { Rol } from './Rol.model';
export class UsuarioAutenticado extends Rol {
  public constructor(
    public id_usuario: string,
    public id: number,
    public rol: string,
    public listado_ventas: boolean,
    public listado_ventas_limitado: string,
    public estado_tanques: boolean,
    public pumptablet: boolean,
    public reporte_turno_cerrados: boolean,
    public reporte_turno_curso: boolean,
    public configuracion_sistema: boolean,
    public consulta_ventas: boolean,
    public consulta_ventas_limitado: string,
    public consulta_comprobantes: boolean,
    public configuracion_comprobantes: boolean,
    public categorias: boolean,
    public productos: boolean,
    public inventario: boolean,
    public ingresos: boolean,
    public roles: boolean,
    public usuarios: boolean,
    public sales: boolean,
    public reporte_turno_periodo: boolean,
    public aperturar_turno: boolean,
    public insertar_cuadre: boolean,
    public bomberos: boolean,
    public configuraciontanques: boolean,
    public expiracion_sesion: number,
    public historial_tanques: boolean,
    public consultar_cuadres: boolean,
    public ingresar_combustible: boolean,
    public egresar_combustible: boolean,
    public movimientos_tanques: boolean,
    public configuracion_horario_turnos: boolean,
    public cerrar_dia: boolean,
    public validar_cuadre: boolean,
    public tpo_prepago: boolean,
    public tpo_cheques: boolean,
    public tpo_vale_credito: boolean,
    public tpo_vale_planta: boolean,
    public tpo_vale_mensajeria: boolean,
    public tpo_vale_consumo: boolean,
    public tpo_calibracion_mezcla: boolean,
    public tpo_calibracion_mantenimiento: boolean,
    public ver_galones_combustible_cuadre: boolean,
    public ver_ventas_combustible_cuadre: boolean,
    public ver_ventas_facturacion_cuadre: boolean,
    public ver_total_vendido_cuadre: boolean,
    public ver_total_tarjeta_cuadre: boolean,
    public ver_total_otros_cuadre: boolean,
    public ver_total_efectivo_cuadre: boolean,
    public anular_pago: boolean,
    public anular_cuadre: boolean,
    public eliminar_apertura: boolean,
    public depositos: boolean,
    public pagos: boolean,
    public permiso_firmante: boolean,
    public cerrar_por_lado: boolean,
    public cerrar_por_dispensador: boolean,
    public aperturar_por_lado: boolean,
    public aperturar_por_dispensador: boolean,
    public aperturar_por_dispensador_sin_importar_turno: boolean,
    public func_abrir_cerrar_seleccionados: boolean,
    public agregar_pagos_cuadre: boolean,
    public agregar_campos_dinamicos_cuadre: boolean,
    public agregar_depositos_cuadre: boolean,
    public acciones_servicio: boolean,
    public cierres_automaticos: boolean,
    public eliminar_deposito: boolean,
    public editar_apertura_cerrada: boolean,
    public prices_changes: boolean,
    public clientes_fidelizados: boolean,
    public suppress_voucher: boolean,
    public exportar_listados: boolean,
    public is_bombero: boolean,
    public modify_voucher: boolean,
    public add_rnc: boolean,
    public configuracion_puntajes_fidelidad: boolean,
    public bombero_open_more_than_one_turn: boolean,
    public add_hour_after_a_pump_can_be_close: boolean,
    public incentivos: boolean,
    public reimprimir_codigo_cliente_fidelizado: boolean,
    public empleados: boolean,
    public flotillas: boolean,
    public reporte_nuevos_clientes_fidelizados: boolean,
    public tpo_pago_contado: boolean,
    public tpo_pago_contado_desc: boolean,
    public autenticar_cierre_turno: boolean,
    public debe_cerrar_todos_lados: boolean,
    public manipulacion_ventas: boolean,
    public creditos: boolean,
    public cliente_creditos: boolean,
    public pagos_creditos: boolean,
    public pagos_contados: boolean,
    public categoria_descuento: boolean,
    public multiple_tarjets: boolean,
    public dashboard: boolean,
    public verifone_type: boolean,
    public close_any_pump: boolean,
    public re_print_ticket_closed_pump: boolean,
    public open_close_pump: boolean,
    public auth_deauth_pump: boolean,
    public multiple_bills: boolean,
    public allow_user_insert_volume_and_price_in_multiple_bills: boolean,
    public allow_create_deposit_without_manual_code:boolean,
    public allow_see_discount_client:boolean,
    public allow_see_discount_product_client:boolean,
    public allow_see_discount_tkt_plu:boolean,
    public allow_close_dispenser_pumptable:boolean,
    public allow_close_day_pumptable:boolean,
    public can_see_new_pump_table:boolean,
  ) {
    super(id, rol, listado_ventas, listado_ventas_limitado, estado_tanques, pumptablet, reporte_turno_cerrados, reporte_turno_curso, configuracion_sistema,
      consulta_ventas, consulta_ventas_limitado, consulta_comprobantes, configuracion_comprobantes, categorias, productos, inventario, ingresos, roles,
      usuarios, sales, reporte_turno_periodo, aperturar_turno, insertar_cuadre, bomberos, configuraciontanques, expiracion_sesion, historial_tanques,
      consultar_cuadres, ingresar_combustible, egresar_combustible, movimientos_tanques, configuracion_horario_turnos, cerrar_dia, validar_cuadre, tpo_prepago,
      tpo_cheques, tpo_vale_credito, tpo_vale_planta, tpo_vale_mensajeria, tpo_vale_consumo, tpo_calibracion_mezcla, tpo_calibracion_mantenimiento,
      ver_galones_combustible_cuadre, ver_ventas_combustible_cuadre, ver_ventas_facturacion_cuadre, ver_total_vendido_cuadre, ver_total_tarjeta_cuadre,
      ver_total_otros_cuadre, ver_total_efectivo_cuadre, anular_pago, anular_cuadre, eliminar_apertura, depositos, pagos, permiso_firmante, cerrar_por_lado,
      cerrar_por_dispensador, aperturar_por_lado, aperturar_por_dispensador, aperturar_por_dispensador_sin_importar_turno, func_abrir_cerrar_seleccionados,
      agregar_pagos_cuadre, agregar_campos_dinamicos_cuadre, agregar_depositos_cuadre, acciones_servicio, cierres_automaticos, eliminar_deposito, editar_apertura_cerrada,
      prices_changes, clientes_fidelizados, suppress_voucher, exportar_listados, is_bombero, modify_voucher, add_rnc, configuracion_puntajes_fidelidad, bombero_open_more_than_one_turn,
      add_hour_after_a_pump_can_be_close, incentivos, reimprimir_codigo_cliente_fidelizado, empleados, flotillas, reporte_nuevos_clientes_fidelizados, tpo_pago_contado,
      tpo_pago_contado_desc, autenticar_cierre_turno, debe_cerrar_todos_lados, manipulacion_ventas, creditos, cliente_creditos, pagos_creditos, pagos_contados,
      categoria_descuento, multiple_tarjets, dashboard, verifone_type, close_any_pump, re_print_ticket_closed_pump, open_close_pump, auth_deauth_pump, multiple_bills,
      allow_user_insert_volume_and_price_in_multiple_bills,allow_create_deposit_without_manual_code,allow_see_discount_client,allow_see_discount_product_client,allow_see_discount_tkt_plu,
      allow_close_dispenser_pumptable,allow_close_day_pumptable,can_see_new_pump_table);


  }
}
